[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
core_staking_example = "J4sLf325UH7YrSUXsNsQs5xCptmS5WuTCYAk6g52phpp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
